### ISSUE TITLE
Both hexo server and generate gets fatal error

### ISSUE THREAD

**Issue by ApolloZhu** [theme-next/theme-next-fastclick#5]
I can confirm that 

- it worked with a previous version of next-util (a git commit not the current version tagged)
- the error disappears after removing hexo-next-share 

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getKeys (~/ApolloZhu.github.io/node_modules/deepmerge/dist/cjs.js:61:16)
    at mergeObject (~/ApolloZhu.github.io/node_modules/deepmerge/dist/cjs.js:86:2)
    at deepmerge (~/ApolloZhu.github.io/node_modules/deepmerge/dist/cjs.js:117:10)
    at module.exports.defaultConfigFile (~/ApolloZhu.github.io/node_modules/next-util/index.js:17:29)
    at ~/ApolloZhu.github.io/node_modules/hexo-next-share/index.js:10:24
    at Array.forEach (<anonymous>)
    at ~/ApolloZhu.github.io/node_modules/hexo-next-share/index.js:9:42
    at Filter.execSync (~/ApolloZhu.github.io/node_modules/hexo/lib/extend/filter.js:76:30)
    at Hexo.execFilterSync (~/ApolloZhu.github.io/node_modules/hexo/lib/hexo/index.js:470:31)
    at module.exports (~/ApolloZhu.github.io/themes/next/scripts/events/lib/injects.js:58:8)
    at Hexo.<anonymous> (~/ApolloZhu.github.io/themes/next/scripts/events/index.js:9:27)
    at Hexo.emit (events.js:317:22)
    at Hexo._generate (~/ApolloZhu.github.io/node_modules/hexo/lib/hexo/index.js:437:10)
    at ~/ApolloZhu.github.io/node_modules/hexo/lib/hexo/index.js:336:19
    at tryCatcher (~/ApolloZhu.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (~/ApolloZhu.github.io/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (~/ApolloZhu.github.io/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (~/ApolloZhu.github.io/node_modules/bluebird/js/release/async.js:86:9)
```

Source: https://github.com/ApolloZhu/ApolloZhu.github.io

**Comment by stevenjoezhang** [comment]
I will change it back to `lodash.merge`
Although it seems wasteful to install the whole `lodash` lib for this purpose 😂

See also https://github.com/hexojs/hexo/issues/4052
